/*
 *  Sound.h
 *  AudioFeatures
 *
 *  Created by Nick Collins on 01/08/2007.
 *  Copyright 2007 Nick Collins. All rights reserved.
 *
 */

#pragma once

//817 audio files
const char *strings[] = {
    
    "/data/audio/mirdata/EMcorpus/PeterManning/A Noite, Porem, Rangeu E Quebrou.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Beachcombers.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Bins And Bells.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Kettle And Cans.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Tins And Tanks.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Buckets And Bolts.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Pots And Pans.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Centoph.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Dreamfile.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Hunt, Jerry_ Fluud for dual Syncl.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Everything Goes When The Whistle.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Chor Der Waisen.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Still Hidden Laughs.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/I Tol D. You So.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/sunSurgeAutomata.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Wasting.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Contraption.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Still Life With Piano.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Martin Butler.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Elmore.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Approximate Rhythms.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Just-More-Idle-Chatter.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Quadro.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Memory Pages.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Notjustmoreidlechatter.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/The Lesson.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Word Color.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Idle Chatter.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Erosphere.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Puzzlasept.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Bocalises.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/D'un Jardin À L'Autre.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Suite N.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/L'invitation Au Départ.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/La Ronde.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/La Roue Ferris.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Touch - Part I.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Touch - Part II.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Expo '85 for multiple synthesizer part1.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Expo '85 for multiple synthesizer part2.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Expo '85 for multiple synthesizer part3.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Expo '85 for multiple synthesizer part4.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Sud (A).wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Sud (B).wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Sud (C).wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Dialogues.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Inharmonique.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Mutations.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Joel Chadabe _ Modalities.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Neil Rolnick & Kathleen Myers _ R.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Neil Rolnick _ A Robert Johnson S.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Carter Scholz _ Oliveros_ Lion's.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Julie Kabat & Neil Rolnick _ Kaba.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Barton McLean _ A Little Night Mu.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Barton McLean _ Demons Of The Nig.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/I Am Sitting In A Room.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Medieval Purity In A Bed Of Thorn.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/With Fish Scales Scattered.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Contours, Clowns And Shadows.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Strings Of Token Strings (1984).wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Nonet_ Computer Music In Four Tra.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Syntax.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Kaleidocycles.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/What Is The Use_.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Lady Neil's Dumpe.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Golem 1.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Arras, for 4 computer-synthesized.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/The Wings of Nike, for computer gI.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/The Wings of Nike, for computer gII.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/The Wings of Nike, for computer gIII.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Pacific, for 4 digital soundtrack I.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Pacific, for 4 digital soundtrack II.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Pacific, for 4 digital soundtrack III.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Pacific, for 4 digital soundtrack IV.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Cage_ Cartridge Music.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Leapday Night - Scene 1.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Leapday Night - Scene 2.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Leapday Night - Scene 3.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/A Traveller's Dream Journal - SetA.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/A Traveller's Dream Journal - SetB.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Interspecies Smalltalk - Part 1.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Interspecies Smalltalk - Part 2.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Mémoires Vives.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/2-01 Symphonie pour un homme seul -.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/2-02 Symphonie… - 2. Partita.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/2-03 Symphonie… - 3. Valse.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/2-04 Symphonie… - 4. Erotica.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/2-05 Symphonie… - 5. Scherzo.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/2-06 Symphonie… - 6. Collectif.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/2-07 Symphonie… - 7. Prosopopée II.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/2-08 Henry (P)_ Symphonie Pour Un Ho.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/2-09 Symphonie… - 9. Apostrophe.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/2-10 Symphonie… - 10. Intermezzo.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/2-11 Symphonie… - 11. Cadence.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/2-12 Symphonie… - 12. Strette.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Riverrun.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/01 Moins l'infini.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/02 Instant 0.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/03 Premières forces - Premières form.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/04 Lumière.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/05 Jeux de configurations.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/06 Échos_mélopée.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/07 Cellules.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/08 Aquatisme.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/09 Polyphonie.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/10 Expression 1.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/11 Expression 2.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/12 Réalité.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Wishart_ Vox 5.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Neptune's Children.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/On the Toon in the Toon on the Ty.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Dreel.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Final Times.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Shortstuff.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/ABZ_A.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Ghosts.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Lifting Bodies.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/01 Motion-Emotion.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/02 Les Couleurs de la Nuit_ animé.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/03 Les Couleurs de la Nuit_ plus ani.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/04 Les Couleurs de la Nuit_ trois an.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/05 Les Couleurs de la Nuit_ lune flo.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/06 Les Couleurs de la Nuit_ bouffées.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/07 Les Couleurs de la Nuit_ nuit noi.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/08 Les Couleurs de la Nuit_ nuit fau.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/09 Les Couleurs de la Nuit_ nuit bla.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/10 Les Couleurs de la Nuit_ nuit dén.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Bruno Degazio _ On Growth and For.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Eric Chasalow _ This Way Out.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Roberto Morales _ Nahual II.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Zack Settel _ Hok Pwah (excerpts).wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Jean-Claude Risset _ Echo (for Jo.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Jonty Harrison _ ...et ainsi de s.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Paulution (Charnel Number Five).wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Dripsody_ An Etude For Variable S.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Ninety-Nine Generators (1956).wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Invocation (1957).wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/The Burning Deck (Without Words).wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Nocturne (1962).wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Music For Expo (1967).wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Safari_ Eine Kleine Klangfarbenme.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Sonic Contours.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Low Speed.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Invention In Twelve Tones.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Fantasy In Space.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Incantation.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Moonflight.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Piece For Tape Recorder.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Kolyosa.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Stereo Electronic Music No.2.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Computer Piece No. 1.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Two Sketches For A Computer Piece I.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Two Sketches For A Computer Piece II.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Synchronisms No. 5.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/The Transformation Of Ani.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Octet I (1952_53) for Tape.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Live EM/01 Than Particle.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Live EM/02 Hornpipe.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Live EM/03 Mesa.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Live EM/04 Horn.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Live EM/05 Medium Size Mograph 1963.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Live EM/Rain Forest Version One.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Live EM/Sliding Pitches Inthe Rain Forest.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Live EM/01 Hpschd One.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Live EM/02 Hpschd Two.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Live EM/03 Hpschd Three.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Live EM/04 Hpschd Four.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Live EM/05 Hpschd Five.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Live EM/06 Hpschd Six.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Live EM/07 Hpschd Seven.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/03 Visages V - Part 1.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/04 Visages V - Part 2.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/05 Visages V - Part 3.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/06 Tête Et Queue Du Dragon - Part 1.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/07 Tête Et Queue Du Dragon - Part 2.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/08 Tautologos 1.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/09 Tautologos 2 - Part 1.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/10 Tautologos 2 - Part 2.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/11 Tautologos 2 - Part 3.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/12 Und So Weiter - Part 1.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/13 Und So Weiter - Part 2.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/14 Und So Weiter - Part 3.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/01 Oscillations.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/02 Seagreen Serenades.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/03 Lovefingers.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/04 Program.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/05 Velvet Cave.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/06 Whirly-Bird.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/07 Dust.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/08 Dancing Gods.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/09 Misty Mountain.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/10 You And I.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/11 Water.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/12 Ruby.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/13 Gypsy Love.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/14 You're Not Fooling Me.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/15 I Have Known Love.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/16 A Pox On You.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/17 Confusion.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/18 Fantasies.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/1-01 Shur, Op.15.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/1-02 Mithra, Op.90.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/1-03 Development 2, Op.24.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/1-04 East-West, Op.45.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/1-05 Chahargah 1, Op.75.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/1-06 Panoptikum 70, Op.27.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/1-07 Stratosphaere 1, Op.46.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/1-08 Yaad, Op.66.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/19 Shock Chords.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/18 The Wizard's Laboratory.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/17 Effervescence.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/16 Celestial Cantabile.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/15 Electrobuild.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/14 Electrostings.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/13 Nightwalker.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/12 Depression.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/11 No Man's Land.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/10 Liquid Energy (Rhythm Only).wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/09 Liquid Energy.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/08 Busy Microbes.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/07 Plodding Power.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/06 Freeze Frame.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/05 The Pattern Emerges.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/04 Frontier Of Knowledge.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/03 Computermatic.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/02 Quest-Fast.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/01 Quest.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/02 Williams Mix.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/23 Overture (Reprise).wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/22 The Homecoming.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/21 The Monster Pursues - Morbius Is.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/20 Come Back to Earth With Me.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/19 Battle With the Invisible Monster.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/18 Robby, the Cook, and 60 Gallons o.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/17 Nothing Like This Claw Found in N.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/16 Giant Footprints in the Sand.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/15 Krell Shuttle Ride and Power Stat.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/14 The Mind Booster - Creation Of Ma.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/13 Ancient Krell Music.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/12 Morbius' Study.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/11 Love At the Swimming Hole.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/10 Robby Arranges Flowers, Zaps Monk.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/09 An Invisible Monster Approaches.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/08 Robby, Make Me a Gown.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/07 Graveyard _ A Night With Two Moon.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/06 A Shangri-La in the Desert _ Gard.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/05 Flurry of Dust _ A Robot Approach.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/04 The Landing.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/03 Once Around Altair.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/02 Deceleration.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/01 Forbidden Planet (Main Title).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc1/Tchaikovsky_ Valse Sentimentale.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc1/Sala_ Concertando Rubato From Elektronische Tanzsuite.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc1/Varèse_ Poem Electronique.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc1/Maxfield_ Sine Music (A Swarm Of Butterfiles Encountered Over The Ocean).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc1/Dockstader_ Apocalypse, Part 2.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc1/Ussachevsky_ Wireless Fantasy.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc1/Babbit_ Philomel.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc1/MEV_ Spacecraft.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc2/Reich_ Pendulum Music.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc2/Yuasa_ Projection Esemplastic For White Noise.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc2/Subotnik_ Silver Apples Of The Moon Part 1.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc2/Tudor_ Rainforest Version 1.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc2/Riley_ Poppy Nogood.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc2/Czukay_ Boat-Woman-Song.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc2/Ferrari_ Music Promenade.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc2/Bayle_ Vibrations Composees - Rosace 3.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc2/Young_ Excerpt _31 _ 69 C.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc3/He Destroyed Her Image.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc3/Six Fantasies On A Poem By Thomas Campion_ Her Song.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc3/En Phase_Hors Phase From Dedans Dehors.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc3/On The Other Ocean.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc3/Stria.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc3/Living Sound, Patent Pending Music For Sound-Joined Rooms Series.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc3/Automatic Writing.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc3/Canti Illuminati.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc3/Music On A Long Thin Wire.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc3/Melange.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc3/Before And After Charm (La Notte).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Ohm/ohm_disc3/Unfamiliar Wind (Leeks Hills).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_1/Klangfiguren II, (1955_56).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_1/Essay, (1957_58).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_1/Terminus I, (1962).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_1/Terminus II, (1966_67).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_1/Output, (1979).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_2/Funktion Rot (1968).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_2/Funktion Grau (1969).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_2/Funktion Violett (1969).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_2/Funktion Blau (1969).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_2/Funktion Indigo (1969).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_3/Petite symphonie intuitive pour un paysage de printemps —1973.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_3/Strathoven —1985.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_3/Presque rien avec filles —1989.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_3/Hétérozygote —1963_64.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_4/Scambi.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_4/Trois visages de Liége (a) l'Air et l'eau.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_4/Trois visages de Liége (b) Voix de la Ville.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_4/Trois visages de Liége (c) Forges.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_4/Paraboles-mix.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_5/Aspekt.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_5/Cry of this earth.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_5/Apocalipsis cum figuris.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_6/Klang Im Unbegrenzsten Raum.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_6/Klangstudie I.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_6/Klangstudie II.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_6/Glockenspiel.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_6/Komposition Nr. 5.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_6/Komposition Nr. 7.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_6/Formanten I - II.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_6/Klangfiguren I.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_6/Seismogramme I - III.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_6/Doppelrohr II.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_6/Incontri Di Fasce Sonore.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_6/Glissandi.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_6/Artikulation.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_6/Interferenzen.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_6/Anepigraphe.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_7/Momeneti.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_7/Thema - Omaggio a Joyce.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_7/Visage.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_7/Le Rire.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_7/Invenzione Su Una Voce.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_8/Points De Fuite.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_8/Marime.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_8/Cartographi Liminaire.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_8/Un Certain Embarquement.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_8/Theme De La Fuite.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_8/Transfert I.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_8/En Abime.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_8/Transfert Ii.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_8/Palimpseste.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_8/Il Ritorno.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_8/Espace _ Escape.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_9/Novars.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_9/Chiaroscuro.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_9/Météores.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Acousmatrix/Acousmatrix_9/Signé Dionysos.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Etude (Konkrete Musik).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Studie I (Elektronische Musik).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Studie II (Elektronische Musik).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Gesang Der Jünglinge (1955-56) (Elektronische Musik).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur I.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur II.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur III.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur IV.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur IX.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur V.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur VI.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur VII.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur VIII.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur X.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur XI.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur XII.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur Xiii A.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur Xiii B.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur Xiii C.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur Xiii D.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur Xiii E.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur Xiii F.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur XIV.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur XV.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur XVI A.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur XVI B.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur XVI C.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur XVI D.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Kontakte (1959-60)_ Struktur XVI E.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Women in electronic music -1977/World Rhythms.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Women in electronic music -1977/Bye Bye Butterfly.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Women in electronic music -1977/I Could Sit Here All Day.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Women in electronic music -1977/Points.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Women in electronic music -1977/New York Social Life.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Women in electronic music -1977/Time To Go.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Eliane Radigue/Transamorem-Transmortem/Transamorem - Transmortem.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Chariots Of Fire/Titles.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Chariots Of Fire/Five Circles.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Chariots Of Fire/Eric's Theme.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Chariots Of Fire/100 Metres.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Switched-On Bach/Bach_ Cantata #29, BWV 29, _Wir Danken Dir, Gott_ - Sinfonia.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Switched-On Bach/Bach_ Orchestral Suite #3 In D, BWV 1068 - Air _On The G String_.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Switched-On Bach/Bach_ 2-Part Invention #8 In F, BWV 779.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Switched-On Bach/Bach_ 2-Part Invention #14 In B Flat, BWV 785.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Switched-On Bach/Bach_ 2-Part Invention #4 In D Minor, BWV 775.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Switched-On Bach/Bach_ Cantata #147, BWV 147, _Herz Und Mund Und Tat Und Leben_ - Jesu Bleibet Meine Freude.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Switched-On Bach/Bach_ Well-Tempered Clavier, Book 1 - Prelude & Fugue #7 In E Flat, BWV 852.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Switched-On Bach/Bach_ Well-Tempered Clavier, Book 1 - Prelude & Fugue #2 In C Minor, BWV 847.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Switched-On Bach/Bach_ Cantata #140, BWV 140, _Wachet Auf, Ruft Uns Die Stimme_ - Sleepers Awake.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Switched-On Bach/Bach_ Brandenburg Concerto #3 In G, BWV 1048 - 1. Allegro.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Switched-On Bach/Bach_ Brandenburg Concerto #3 In G, BWV 1048 - 2. Adagio.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Switched-On Bach/Bach_ Brandenburg Concerto #3 In G, BWV 1048 - 3. Allegro.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Auto-Lite_ Spark Plugs.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Auto-Lite_ Sta-Ful.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Awake.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/B.C. 1675.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Backwards Overload.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Baltimore Gas & Electric Co. _395_.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Baltimore Gas & Electric Co..wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Bandito The Bongo Artist.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Bendix _The Tomorrow People_.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Bufferin_ _Memories_ (Original).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Cheer_ Revision 3.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/County Fair.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Domino.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Don't Beat Your Wife Every Night.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/GMGM 1A.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Good Air.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/IBM MT_ST _ _The Paperwork Explosion_.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/IBM Probe.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/K2r.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Lady Gaylord.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Lightworks.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Limbo_ The Organized Mind.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Manhattan Research, Inc. Copyright.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Nescafe.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Night And Day.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Portofino.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Sprite _Melonball Bounce_ 1.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Sprite _Melonball Bounce_.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Super Cheer.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/The Bass-Line Generator.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/The Rhythm Modulator.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Twilight In Turkey.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Vicks_ Formula 44.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Vicks_ Medicated Cough Drops.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Vim.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 1]/Wheels That Go.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/_The Paperwork Explosion_ (Instr.).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Auto-Lite_ _Wheels_.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Auto-Lite_ Ford Family (Instr.).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Auto-Lite_ Ford Family.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Auto-Lite_ Sta-Ful.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Backward Beeps.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Baltimore Gas & Electric Co. (Announce Copy, Take 1).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Baltimore Gas & Electric Co..wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Bendix 2_ The Tomorrow People.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Bufferin_ _Memories_ (Demo).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Cindy Electronium.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/County Fair (Instrumental).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Cyclic Bit.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Don't Beat Your Wife Every Night! (Instr.).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Electronic Audio Logos, Inc..wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/General Motors_ Futurama.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Hostess_ Twinkies (Instr.).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Hostess_ Twinkies.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/In The Hall Of The Mountain Queen.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Lightworks (Instr.).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Lightworks (Slow).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Ohio Bell_ Thermo Fax.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Ohio Plus.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Portofino 2.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Ripples (Montage).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Ripples (Original Soundtrack).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Space Mystery (Montage).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/Take Me To Your Violin Teacher.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/The Pygmy Taxi Corporation.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/The Toy Trumpet.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/The Wild Piece.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/The Wing Thing.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Manhattan Research, Inc. [Disc 2]/When Will It End_.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/The Expanding Universe/A Folk Study.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/The Expanding Universe/Appalachian Grove I.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/The Expanding Universe/Appalachian Grove II.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/The Expanding Universe/Appalachian Grove III.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/The Expanding Universe/Clockworks.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/The Expanding Universe/Dirge Part I.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/The Expanding Universe/Dirge Part II.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/The Expanding Universe/Drums.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/The Expanding Universe/East River Dawn.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/The Expanding Universe/Kepler's Harmony of the Worlds.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/The Expanding Universe/Music for Dance part I.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/The Expanding Universe/Music for Dance part II.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/The Expanding Universe/Old Wave.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/The Expanding Universe/Patchwork.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/The Expanding Universe/Pentachrome.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/The Expanding Universe/The Expanding Universe.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/The Expanding Universe/The Orient Express.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/The Expanding Universe/The Unquestioned Answer.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/The Expanding Universe/Wandering in Our Times.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Revolution 9.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Silicon Valley Breakdown.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Amphitryon 38.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/The Ocean (Main Theme).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Quatermass And The Pit (Effects).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Major Bloodnok's Stomach.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Outside.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Science And Industry.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/The Artist Speaks.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/The Splendour That Was Rome.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/TV March.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Interval Signal.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Phra The Phoenician.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Full Circle - The Stick Up.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Time Beat.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Music For A Magic Carpet.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Ideal Home Exhibition.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Time On Our Hands (Titles And City Music).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Arabic Science And Industry.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/The Chem Lab Mystery.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Know Your Car (Get Out And Get Under).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Doctor Who.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Tardis.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Choice.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Hard Luck Hall.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Westminster At Work.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Talk Out.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Science And Health.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Secrets Of The Chasm.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/The Slide (Opening).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/A New View Of Politics.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Radio Stoke-on-Trent (1).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Radio Stoke-on-Trent (2).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Bobby Shaftoe.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/The Lambton Worm.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Environmental Studies.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Chronicle.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Great Zoos Of The World.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/P.M. (1970).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Tros Y Gareg (Over The Stone).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Dance From \"Noah\".wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Good Morning Wales.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Sequence.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Martian March Past.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/The Changes (Suite).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Thomas The Rhymer.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Merry-Go-Round.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Fanfare.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/BBC2 Serial.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/The Plunderers.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/The Secret War.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Quirky.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Newton.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Contact.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/For Love Or Money.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Mysterioso.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/The Astronauts.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Moving Form (Main Theme From \"The Body In Question\").wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/A Whisper From Space.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Land And People.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Swirley.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Greenwich Chorus.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Hurdy Gurdy.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/P.M. (1978).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Broken Biscuit Club.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/The Unseeing Eye.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/The Milonga.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Mainstream.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Seascape.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/bbcradiophonic/Yellow Moon.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Popular Electronics/CD 1/Kaïn En Abel - 1.1 - Introduction _ Dance of the Destructive Forces.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Popular Electronics/CD 1/Kaïn En Abel - 1.2 - Conflict, Conclusion, Transition.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Popular Electronics/CD 1/Kaïn En Abel - 2.1 - Passacaglia.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Popular Electronics/CD 1/Kaïn En Abel - 2.2 - Arioso.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Popular Electronics/CD 1/Kaïn En Abel - 2.3 - Conflict, Reprise (Arioso).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Popular Electronics/CD 1/Kaïn En Abel - 2.4 - Conflict, Finale.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Popular Electronics/CD 1/Evolutionen - 1_ Overture.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Popular Electronics/CD 1/Evolutionen - 2_ Air.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Popular Electronics/CD 1/Evolutionen - 3_ Ragtime.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Popular Electronics/CD 1/Evolutionen - 4_ Intermezzo.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Popular Electronics/CD 1/Evolutionen - 5_ Waltz.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Popular Electronics/CD 1/Evolutionen - 6_ Finale.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Popular Electronics/CD 2/Variations Électroniques_ A Light and Frolic Experiment in Sound and Movement.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/EvolutionMoroderBattlestarGalactica1978.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Blade Runner/Blade Runner (End Titles).wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Blade Runner/Blush Response.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Blade Runner/Main Titles.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Blade Runner/Tears In Rain.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Blade Runner/Wait For Me.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Escape From New York/69th Street Bridge.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Escape From New York/Arrival At The Library.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Escape From New York/Engulfed Cathedral (Debussy).wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Escape From New York/Main Title.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Escape From New York/Orientation.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Escape From New York/Over The Wall _ Airforce One.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Escape From New York/Police Action.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Escape From New York/President At The Train.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Escape From New York/Romero And The President.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Escape From New York/The Duke Arrives _ Barricade.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Escape From New York/The President Is Gone.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Clockwork Orange - Complete Original Score/March From A Clockwork Orange (Ninth Symphony, Fourth Movement, Abridged).wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Clockwork Orange - Complete Original Score/Ninth Symphony_ Second Movement (Scherzo).wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Clockwork Orange - Complete Original Score/Theme From A Clockwork Orange (Beethoviana).wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Clockwork Orange - Complete Original Score/Timesteps.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Clockwork Orange - Complete Original Score/Title Music From A Clockwork Orange.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Clockwork Orange - Complete Original Score/William Tell Overture, Abridged.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Midnight Express/Cacophony.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Midnight Express/Chase.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Midnight Express/Istanbul Opening.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Midnight Express/The Wheel.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Tron - Original Motion Picture Soundtrack/Theme From Tron.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Tron - Original Motion Picture Soundtrack/Tron Scherzo.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Sonic Seasonings/Fall.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Sonic Seasonings/Spring.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Sonic Seasonings/Summer.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Sonic Seasonings/Winter.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Else Marie Pade/Etude (1962).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Else Marie Pade/Faust Suite_ Epilog.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Else Marie Pade/Faust Suite_ Faust & Margrethes Kærlighed.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Else Marie Pade/Faust Suite_ Faust & Mefisto.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Else Marie Pade/Faust Suite_ Margrethes Fordømmelse.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Else Marie Pade/Faust Suite_ Prolog I Himlen.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Else Marie Pade/Faust Suite_ Rejsen Til Bloksbjerg Og Valborgsnat.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Else Marie Pade/Glasperlespil I (1960).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Else Marie Pade/Glasperlespil II (1960).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Else Marie Pade/Lyd & Lys (1960).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Else Marie Pade/Syv Cirkler (1958).wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Seven Waves/The Fifth Wave_ Water Lullaby.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Seven Waves/The First Wave_ Birth Of Venus.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Seven Waves/The Fourth Wave_ Wind In The Sea.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Seven Waves/The Second Wave_ Sirens.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Seven Waves/The Seventh Wave_ Sailing Away.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Seven Waves/The Sixth Wave_ Deep In The Sea.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Seven Waves/The Third Wave_ Love In The Waves.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Soothing Sounds for Baby Vol. 1/Lullaby.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Soothing Sounds for Baby Vol. 1/Nursery Rhyme.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Soothing Sounds for Baby Vol. 1/Sleepy Time.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Soothing Sounds for Baby Vol. 1/The Music Box.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Raymond Scott/Soothing Sounds for Baby Vol. 1/Tic Toc.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/The Electric Lucifer/Angel Child.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/The Electric Lucifer/Chant of The Unborn.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/The Electric Lucifer/Cherubic Hymn.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/The Electric Lucifer/Electric To Me Turn.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/The Electric Lucifer/Incantation.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/The Electric Lucifer/National Anthem To The Moon.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/The Electric Lucifer/Program Me.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/The Electric Lucifer/Requiem.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/The Electric Lucifer/Song Of The Death Machine.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/The Electric Lucifer/Super Nova.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/The Electric Lucifer/The Word (Narration).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/The Electric Lucifer/War.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/The Electric Lucifer/Word Game.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/Farad The Electric Voice/Ancient Mariner.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/Farad The Electric Voice/Epilogue.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/Farad The Electric Voice/Lie Back.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/Farad The Electric Voice/Man Kind.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/Farad The Electric Voice/Maybe This Song.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/Farad The Electric Voice/Noon Day Sun.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/Farad The Electric Voice/Party Machine.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/Farad The Electric Voice/Program Me.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/Farad The Electric Voice/Rain Of Earth.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/Farad The Electric Voice/Rita.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/Farad The Electric Voice/Snow Job.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/Farad The Electric Voice/Stand Up Lazarus.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/Farad The Electric Voice/The King.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/The Wayout Record For Children/Nothing To Do.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/The Wayout Record For Children/Rubberbands.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/The Wayout Record For Children/School For Robots.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Bruce Haack/The Wayout Record For Children/Tools.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Computer Music Currents 5/Jardin Secret 1.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Computer Music Currents 5/Mortuos Plango, Vivos Voco.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Computer Music Currents 5/Nekyia.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Computer Music Currents 5/Wind Chimes.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/An Electric Storm/Love Without Sound.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/An Electric Storm/My Game Of Loving.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/An Electric Storm/Here Come The Fleas.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/An Electric Storm/Firebird.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/An Electric Storm/Your Hidden Dreams.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/An Electric Storm/The Visitation.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/An Electric Storm/Black Mass_ An Electric Storm In Hell.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Jazz from Hell/Night School.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Jazz from Hell/The Beltway Bandits.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Jazz from Hell/While You Were Art II.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Jazz from Hell/Jazz From Hell.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Jazz from Hell/G-Spot Tornado.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Jazz from Hell/Damp Ankles.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Jazz from Hell/Massaggio Galore.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Snowflakes Are Dancing/Snowflakes Are Dancing.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Snowflakes Are Dancing/Reverie.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Snowflakes Are Dancing/Gardens In The Rain.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Snowflakes Are Dancing/Clair De Lune.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Snowflakes Are Dancing/Arabesque No. 1.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Snowflakes Are Dancing/The Engulfed Cathedral.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Snowflakes Are Dancing/Passepied.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Snowflakes Are Dancing/The Girl With The Flaxen Hair.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Snowflakes Are Dancing/Golliwog's Cakewalk.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Snowflakes Are Dancing/Footprints In The Snow.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Snowflakes Are Dancing/Prelude To The Afternoon Of A Faun.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Messe Pour Le Temps Présent/Henry_ Messe Pour Le Temps Présent - Prologue.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Messe Pour Le Temps Présent/Henry_ Messe Pour Le Temps Présent - Psyché Rock.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Messe Pour Le Temps Présent/Henry_ Messe Pour Le Temps Présent - Jericho Jerk.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Messe Pour Le Temps Présent/Henry_ Messe Pour Le Temps Présent - Teen Tonic.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Messe Pour Le Temps Présent/Henry_ Messe Pour Le Temps Présent - Too Fortiche.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Messe Pour Le Temps Présent/Henry_ La Reine Vert - Marche Du Jeune Homme.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Messe Pour Le Temps Présent/Henry_ La Reine Vert - Rock Électronique.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Messe Pour Le Temps Présent/Henry_ Le Voyage - Le Couple.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Messe Pour Le Temps Présent/Henry_ Le Voyage - Fluidité Et Mobilité D'Un Larsen.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Messe Pour Le Temps Présent/Henry_ Le Voyage - Divinités Paisibles.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Messe Pour Le Temps Présent/Henry_ Variations Pour Une Porte Et Un Soupir - Balancement.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Messe Pour Le Temps Présent/Henry_ Variations Pour Une Porte Et Un Soupir - Chant 1.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Messe Pour Le Temps Présent/Henry_ Variations Pour Une Porte Et Un Soupir - Éveil.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Messe Pour Le Temps Présent/Henry_ Variations Pour Une Porte Et Un Soupir - Chant 2.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Messe Pour Le Temps Présent/Henry_ Variations Pour Une Porte Et Un Soupir - Étirement.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Messe Pour Le Temps Présent/Henry_ Variations Pour Une Porte Et Un Soupir - Gestes.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Messe Pour Le Temps Présent/Henry_ Variations Pour Une Porte Et Un Soupir - Comptine.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Messe Pour Le Temps Présent/Henry_ Variations Pour Une Porte Et Un Soupir - Fièvre 1.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Messe Pour Le Temps Présent/Henry_ Variations Pour Une Porte Et Un Soupir - Gymnastique.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Messe Pour Le Temps Présent/Henry_ Variations Pour Une Porte Et Un Soupir - Fièvre 2.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 1]/Introduction.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 1]/Power Tools.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 1]/Bird Of Parallax.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 1]/Contrasts Esconic.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 1]/Lego Builds It.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 1]/Pompie Ballet [Excerpt].wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 1]/Intertel.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 1]/Adwick High School No.1.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 1]/Look At Oramics.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 1]/Rotolock.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 1]/Purple Dust.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 1]/High Speed Flight.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 1]/Four Aspects.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 1]/Kia Ora.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 1]/Dr. Faustus Suite.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 1]/Tumblewash.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 1]/Snow.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 2]/Rockets In Ursa Major [Excerpt 1].wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 2]/Food Preservation.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 2]/Episode Metallic.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 2]/Fanfare Of Graphs.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 2]/Brociliande.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 2]/Mary Had A Little Lamb.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 2]/Incidental Music For Invasion [Excerpts].wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 2]/Costain Suite.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 2]/Passacaglia.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 2]/Missile Away.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 2]/Pulse Persephone.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Oramics [Disc 2]/Nestea.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/The Historical CD of Digital Sound Synthesis/Ferretti _ Pipe and Drum (1963).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/The Historical CD of Digital Sound Synthesis/Ferretti _ Trio (1965).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/The Historical CD of Digital Sound Synthesis/Guttman _ Pitch Variations (1957).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/The Historical CD of Digital Sound Synthesis/Guttman _ The Silver Scale (1957).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/The Historical CD of Digital Sound Synthesis/Lewin _ Study no.1 (1961).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/The Historical CD of Digital Sound Synthesis/Lewin _ Study no.2 (1961).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/The Historical CD of Digital Sound Synthesis/Mathews _ International Lullaby (1966).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/The Historical CD of Digital Sound Synthesis/Mathews _ Masquerades (1963).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/The Historical CD of Digital Sound Synthesis/Mathews _ Numerology (1960).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/The Historical CD of Digital Sound Synthesis/Mathews _ The Second Law (1961).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/The Historical CD of Digital Sound Synthesis/Mathews arr. _ Bicycle Built for Two.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/The Historical CD of Digital Sound Synthesis/Pierce _ Eight-Tone Canon (1966).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/The Historical CD of Digital Sound Synthesis/Pierce _ Sea Sounds (1963).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/The Historical CD of Digital Sound Synthesis/Pierce _ Stochatta (1959).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/The Historical CD of Digital Sound Synthesis/Pierce _ Variation in Timbre and Attack (1961).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/The Historical CD of Digital Sound Synthesis/Randall _ Mudgett, Monologues for a Mass Murderer (1965).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/The Historical CD of Digital Sound Synthesis/Tenney _ Dialogue (1963).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/George Harrison/Electronic Sound/No Time Or Space.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/George Harrison/Electronic Sound/Under The Mersey Wall.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Roberto Gerhard Electronic Explorations from His Studio + The BBC Radiophonic Workshop 1958-1967/Audiomobile 'In the Manner of Goya'.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Roberto Gerhard Electronic Explorations from His Studio + The BBC Radiophonic Workshop 1958-1967/Audiomobiles I 'Sculpture'.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Roberto Gerhard Electronic Explorations from His Studio + The BBC Radiophonic Workshop 1958-1967/Audiomobiles II 'DNA in Reflection'.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Roberto Gerhard Electronic Explorations from His Studio + The BBC Radiophonic Workshop 1958-1967/Audiomobiles III 'Sculpture'.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Roberto Gerhard Electronic Explorations from His Studio + The BBC Radiophonic Workshop 1958-1967/Caligula.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Eliane Radigue/Triptych/Triptypch Part 1.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Eliane Radigue/Triptych/Triptypch Part 2.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Eliane Radigue/Triptych/Triptypch Part 3.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Peter Zinovieff/Chronometer.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Peter Zinovieff/A Lollipop For Papa.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Peter Zinovieff/Agnus Dei.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Peter Zinovieff/Now's The Time To Say Goodbye.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Peter Zinovieff/Raasay Digitised.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Peter Zinovieff/Tarantella.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Peter Zinovieff/ZASP.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 1 Les Visiteurs De L'Aventure Concrète/Aspect Sentimental.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 1 Les Visiteurs De L'Aventure Concrète/Déserts - Interpolation 1.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 1 Les Visiteurs De L'Aventure Concrète/Etude I.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 1 Les Visiteurs De L'Aventure Concrète/Etude II.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 1 Les Visiteurs De L'Aventure Concrète/Etude.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 1 Les Visiteurs De L'Aventure Concrète/Jazz et jazz.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 1 Les Visiteurs De L'Aventure Concrète/L'Amen De Verre.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 1 Les Visiteurs De L'Aventure Concrète/Points-Mouvements.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 1 Les Visiteurs De L'Aventure Concrète/Texte 2.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 1 Les Visiteurs De L'Aventure Concrète/Timbres-Durées.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 2 L'art De L'étude/Boîte À Musique (1955).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 2 L'art De L'étude/Étude 1 (1960).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 2 L'art De L'étude/Étude 2 (1962).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 2 L'art De L'étude/Étude Aux Accidents (1958).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 2 L'art De L'étude/Étude Aux Allures (1958).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 2 L'art De L'étude/Étude Aux Objets, 1er Mvt (1959).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 2 L'art De L'étude/Étude Aux Sons Réalistes (1969).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 2 L'art De L'étude/Étude Aux Sons Tendus (1958).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 2 L'art De L'étude/Étude Floue (1958).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 2 L'art De L'étude/Étude No 1 (1952).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 2 L'art De L'étude/Étude Numérique (1985).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 2 L'art De L'étude/Étude Vocale (1952).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 2 L'art De L'étude/Mer d'Azov, Étude Aux Itérations (1960).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 2 L'art De L'étude/Prélude.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Archives GRM/Disc 2 L'art De L'étude/Reflets (1961).wav",
    "/data/audio/mirdata/EMcorpus/pioneers/anthology/Mandolin.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/anthology/Quintet.wav",
    "/data/audio/mirdata/EMcorpus/synthinstrumental/Discreet Music.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Xenakis/Bohor.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Xenakis/Concret PH.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Xenakis/Diamorphoses.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Xenakis/Gendy 3.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Xenakis/Hibiki-Hana-Ma.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Xenakis/Orient-Occident.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Xenakis/S.709.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Xenakis/Taurhiphanie.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Bernard Parmegiani/De Natura Sonorum/Accidents_Harmoniques.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Bernard Parmegiani/De Natura Sonorum/Conjugaison Du Timbre.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Bernard Parmegiani/De Natura Sonorum/Dynamique De La Résonance.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Bernard Parmegiani/De Natura Sonorum/Étude Élastique.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Bernard Parmegiani/De Natura Sonorum/Géologie Sonore.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Bernard Parmegiani/De Natura Sonorum/Incidences_Battements.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Bernard Parmegiani/De Natura Sonorum/Incidences_Résonances.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Bernard Parmegiani/De Natura Sonorum/Matières Induites.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Bernard Parmegiani/De Natura Sonorum/Natures Éphémères.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Bernard Parmegiani/De Natura Sonorum/Ondes Croisées.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Bernard Parmegiani/De Natura Sonorum/Pliens Et Déliés.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Bernard Parmegiani/De Natura Sonorum/Points Contre Champs.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/anthology/Broken music composition.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/anthology/Demeures aquatiques.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/anthology/Pièce électronique no. 3.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/anthology/Sediment.wav",
    "/data/audio/mirdata/EMcorpus/pioneers/Stockhausen/Telemusik.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Elsa Justel/Alba Sud.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Elsa Justel/Au loin... bleu.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Elsa Justel/Du libe tu?.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Elsa Justel/Mâts.wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Hildegard Westerkamp/Beneath The Forest Floor (1992).wav",
    "/data/audio/mirdata/EMcorpus/electroacoustic/Hildegard Westerkamp/Cricket Voice (1987).wav"
};


//{"one","two","three"};
